name: Continuous integration

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - '**/*.md'
  workflow_call:
    outputs:
      version:
        description: Version of the built fonts
        value: ${{ jobs.build-fonts.outputs.version }}

jobs:
  build-fonts:
    name: Build fonts
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get install -y fontforge python3-fontforge
          pip install -r requirements.txt
      - name: Cache downloads
        id: cache-downloads
        uses: actions/cache@v4
        with:
          path: downloads
          key: ${{ runner.os }}-downloads
      - name: Build
        id: build
        run: ./build.py
      - uses: actions/upload-artifact@v4
        with:
          name: fonts
          path: dist
